import Head from 'next/head'



const Headbar = () => {
    return (
        <>
            <Head>
                <title>My Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <script src="https://cdn.tailwindcss.com"></script>
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
        </>
    )
}

export default Headbar
